blog/urls.py
from django.contrib import admin
from django.urls import path
from django.shortcuts import render

from django.urls import include
from blog.views import *
app_name = "blog"

urlpatterns = [
    path('', PostView.post_list, name='main'),
    path('post/<int:id>', PostView.show_post, name='show_post'),
    path('comment', PostView.do_comment, name='do_comment'),
    path('post/new/', PostView.post_new, name='post_new'),
    path('post/<int:id>/edit', PostView.post_edit, name='post_new'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

blog/models.py
# Create your models here.
from django.contrib.auth.models import User
# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(User, on_delete='RESTRICT')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete='RESTRICT', related_name='comments')
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now)

    def __str__(self):
        return self.text

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect

from blog.models import *
from .forms import PostForm


class PostView:
    # Create your views here.
    @staticmethod
    def post_list(request):
        posts = Post.objects.order_by('-published_date').all()
        return render(request, 'blog/post_list.html', {'posts': posts})

    @staticmethod
    def index(request):
        return render(request, 'blog/index.html', {})

    @staticmethod
    def show_post(request, id: int):
        post = get_object_or_404(Post, pk=id)
        comments = post.comments.order_by('-id').all()
        return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments})

    @staticmethod
    def do_comment(request):
        if request.method == 'POST':
            id = request.POST.get('id')
            name = request.POST.get('name')
            text = request.POST.get('content')
            Comment.objects.create(author=name, text=text, post_id=id)
            return redirect("blog:show_post", id=id)

        return Http404("404 Not Found")

    @staticmethod
    def post_new(request):
        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                return redirect("blog:show_post", id=post.pk)
        else:
            form = PostForm()
        return render(request, 'blog/post_edit.html', {'form': form})

    @staticmethod
    def post_edit(request, id):
        post = get_object_or_404(Post, id=id)
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                return redirect('blog:show_post', id=post.id)
        else:
            form = PostForm(instance=post)
            return render(request, 'blog/post_edit.html', {'form': form})

blog/templates/blog/base.html
{% load staticfiles %}
<html>
<head>
    <title>Django Girls blog</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
{#    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>#}
    <link href='http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
<div class="page-header">
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>

    <h1><a href="/">Django Girls Blog</a></h1>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

blog/templates/blog/index.html
Hello world

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="date">
        {% if post.published_date %}
            {{ post.published_date }}
        {% endif %}
    </div>
    <h1>{{ post.title }}</h1>
    <p style="white-space: pre-line">{{ post.text }}</p>

    <hr/>
    <h2>Comments</h2>
    {% for comment in comments %}
        <div class="comment">
            <p>published: {{ comment.published_date }} / by: {{ comment.author }}</p>
            <p style="white-space: pre-line">{{ comment.text }}</p>
        </div>
        <hr/>
    {% endfor %}
    <hr/>
    <h3>Leave a comment</h3>
    <form method="POST" class="form" action="{% url 'blog:do_comment' %}">
        <p class="form-group">
            <label for="name">Name:</label>
            <input type="text" name="name" id="name" required class="form-control">
        </p>
        <p class="form-group">
            <label for="content">Content</label>
            <textarea name="content" id="content" class="form-control"></textarea>
        </p>
        <p>
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ post.pk }}"/>
            <button type="submit" class="btn btn-warning">Comment</button>
        </p>
    </form>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p>published: {{ post.published_date }}</p>
            <h1><a href="{% url 'blog:show_post' id=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaks }}</p>
        </div>
    {% endfor %}
{% endblock content %}

blog/templates/blog/show.html
<p>{{ post.id }}</p>
{% for i in "123456789" %}
    <p>{{ i }}</p>
{% endfor %}

{{ test }}